FROM node:14

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

EXPOSE 3001

ENV MONGODB_URI=mongodb://mongo:27017/mydatabase
ENV NODE_ENV=production

CMD ["npm", "start"]